name: BeeChat
main: com.github.kotqwerty.beechat.BeeChat
version: '$version'
api-version: '1.21.10'
authors:
  - KotQWERTY
dependencies:
  server:
    MiniPlaceholders:
      required: false
      load: BEFORE
    PlaceholderAPI:
      required: false
      load: BEFORE
